### ISSUE TITLE
Change: Remove "lizard hissing"

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/revstation#8]
Remove the obnoxious character-replacement when lizards talk.

**Comment by dalmationer** [comment]
Replace with pesterchum style text replacer in chargen in case someone likes it?

**Comment by dalmationer** [comment]
Also; there are still some references to lizard racism in the game, e.g. Graffiti that's pro- or anti- lizard. It's real annoying.

**Comment by Profakos** [comment]
Lizard speech is part of the tongue code, the modify_speech proc's override. 

I would handle this with a pref like spines and tails, where you can swap between normal lizard tongue, or one that is accentless, and make the lizard tongue return speech without modification if accentless is selected. 
I would replace the tongue in this proc:
https://github.com/tgstation/tgstation/blob/63b0fad930b848659f26b93fa932782d14afe44b/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm#L103
before the parent is called, and overwrite the mutanttongue in the datum based on dna.features, as this would mean, it you regenerated your organs at a later time, you would keep your accent/accentlesness properly.

Its a datum so it would be unique per person.

**Comment by Profakos** [comment]
Fixed in #13
